export const SET_DATA = "SET_DATA";
export const RESET_DATA = "RESET_DATA";
export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RESOLVED = "REQUEST_RESOLVED";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const REQUEST_FAILURE_ACKNOWLEDGED = "REQUEST_FAILURE_ACKNOWLEDGED";
export const RESET_LOADING_AND_ALERTS = "RESET_LOADING_AND_ALERTS";
